# Generated by Django 5.1.2 on 2024-11-19 07:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="file",
            name="user",
        ),
        migrations.CreateModel(
            name="ChatHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField()),
                ("answer", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("conversation_id", models.CharField(max_length=100)),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="documents/")),
                ("filename", models.CharField(max_length=255)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProcessedIndex",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "faiss_index",
                    models.CharField(
                        help_text="Path to saved FAISS index file", max_length=255
                    ),
                ),
                (
                    "metadata",
                    models.CharField(
                        help_text="Path to saved metadata file", max_length=255
                    ),
                ),
                (
                    "summary",
                    models.TextField(help_text="Generated summary of the document"),
                ),
                (
                    "markdown_path",
                    models.CharField(
                        help_text="Path to saved Markdown file with key terms",
                        max_length=255,
                    ),
                ),
                (
                    "follow_up_question_1",
                    models.TextField(
                        blank=True, help_text="First follow-up question", null=True
                    ),
                ),
                (
                    "follow_up_question_2",
                    models.TextField(
                        blank=True, help_text="Second follow-up question", null=True
                    ),
                ),
                (
                    "follow_up_question_3",
                    models.TextField(
                        blank=True, help_text="Third follow-up question", null=True
                    ),
                ),
                ("processed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "document",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="chat.document"
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Conversation",
        ),
        migrations.DeleteModel(
            name="File",
        ),
    ]
