# Generated by Django 5.1.2 on 2024-12-03 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0004_conversation_message"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="conversation",
            name="user",
        ),
        migrations.RemoveField(
            model_name="message",
            name="conversation",
        ),
        migrations.RemoveIndex(
            model_name="chathistory",
            name="chat_chathi_user_id_0576dd_idx",
        ),
        migrations.RemoveIndex(
            model_name="chathistory",
            name="chat_chathi_is_acti_14b8a2_idx",
        ),
        migrations.RemoveField(
            model_name="chathistory",
            name="document_context",
        ),
        migrations.RemoveField(
            model_name="chathistory",
            name="last_message_at",
        ),
        migrations.AlterField(
            model_name="chathistory",
            name="conversation_id",
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name="Conversation",
        ),
        migrations.DeleteModel(
            name="Message",
        ),
    ]
