# Generated by Django 5.1.4 on 2024-12-08 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0006_alter_chathistory_options_remove_chathistory_answer_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConversationMemoryBuffer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key_entities", models.JSONField(blank=True, null=True)),
                ("context_summary", models.TextField(blank=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "conversation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memory_buffer",
                        to="chat.chathistory",
                    ),
                ),
            ],
        ),
    ]
